//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayando.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayando.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string AccountChangePassword {
            get {
                return ResourceManager.GetString("AccountChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким email уже зарегистрирован.
        /// </summary>
        public static string AccountController_Register_Пользователь_с_таким_email_уже_зарегистрирован {
            get {
                return ResourceManager.GetString("AccountController_Register_Пользователь_с_таким_email_уже_зарегистрирован", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст с картинки введен неверно.
        /// </summary>
        public static string AccountController_Register_Текст_с_картинки_введен_неверно {
            get {
                return ResourceManager.GetString("AccountController_Register_Текст_с_картинки_введен_неверно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string AccountLogOff {
            get {
                return ResourceManager.GetString("AccountLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string AccountLogOn {
            get {
                return ResourceManager.GetString("AccountLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AccountLogonPasswordLabelText {
            get {
                return ResourceManager.GetString("AccountLogonPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string AccountLogonRegister {
            get {
                return ResourceManager.GetString("AccountLogonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me on this machine.
        /// </summary>
        public static string AccountLogonRememberMeCheckBoxText {
            get {
                return ResourceManager.GetString("AccountLogonRememberMeCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string AccountLogonUserLabelText {
            get {
                return ResourceManager.GetString("AccountLogonUserLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string AccountRegisterConfirmPassword {
            get {
                return ResourceManager.GetString("AccountRegisterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail:.
        /// </summary>
        public static string AccountRegisterEmail {
            get {
                return ResourceManager.GetString("AccountRegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string AccountRegisterPassword {
            get {
                return ResourceManager.GetString("AccountRegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string AccountRegisterUserName {
            get {
                return ResourceManager.GetString("AccountRegisterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulate sewing.
        /// </summary>
        public static string ButtonAnimateText {
            get {
                return ResourceManager.GetString("ButtonAnimateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDeleteText {
            get {
                return ResourceManager.GetString("ButtonDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Published.
        /// </summary>
        public static string CalendarByDatePublished {
            get {
                return ResourceManager.GetString("CalendarByDatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Taken.
        /// </summary>
        public static string CalendarByDateTaken {
            get {
                return ResourceManager.GetString("CalendarByDateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CommentsTitle {
            get {
                return ResourceManager.GetString("CommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string ContactAuthorEmail {
            get {
                return ResourceManager.GetString("ContactAuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ContactAuthorMessage {
            get {
                return ResourceManager.GetString("ContactAuthorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string ContactAuthorName {
            get {
                return ResourceManager.GetString("ContactAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me on this computer.
        /// </summary>
        public static string ContactAuthorRememberMe {
            get {
                return ResourceManager.GetString("ContactAuthorRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string ContactAuthorUrl {
            get {
                return ResourceManager.GetString("ContactAuthorUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me.
        /// </summary>
        public static string ContactContactMe {
            get {
                return ResourceManager.GetString("ContactContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string ContactNotes {
            get {
                return ResourceManager.GetString("ContactNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization:.
        /// </summary>
        public static string ContactOrganization {
            get {
                return ResourceManager.GetString("ContactOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site URL:.
        /// </summary>
        public static string ContactSiteURL {
            get {
                return ResourceManager.GetString("ContactSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ContactSubmit {
            get {
                return ResourceManager.GetString("ContactSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string ContactSurname {
            get {
                return ResourceManager.GetString("ContactSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is in demo mode. You can see all settings as an administrator would, but you cannot change anything..
        /// </summary>
        public static string DemoModePageFlash {
            get {
                return ResourceManager.GetString("DemoModePageFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download DST.
        /// </summary>
        public static string DownloadDSTButtonText {
            get {
                return ResourceManager.GetString("DownloadDSTButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download embroidery file.
        /// </summary>
        public static string EmbroDownloadButtonText {
            get {
                return ResourceManager.GetString("EmbroDownloadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embroidery file name to be upload.
        /// </summary>
        public static string EmbroFileToBeUploadName {
            get {
                return ResourceManager.GetString("EmbroFileToBeUploadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again or notify the site administrator..
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galleries.
        /// </summary>
        public static string GalleriesTitle {
            get {
                return ResourceManager.GetString("GalleriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (More).
        /// </summary>
        public static string GalleryPhotoLinkMore {
            get {
                return ResourceManager.GetString("GalleryPhotoLinkMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string GenerateButtonText {
            get {
                return ResourceManager.GetString("GenerateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value.
        /// </summary>
        public static string IncorrectNumberValue {
            get {
                return ResourceManager.GetString("IncorrectNumberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string LabelTextHello {
            get {
                return ResourceManager.GetString("LabelTextHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LatitudeText {
            get {
                return ResourceManager.GetString("LatitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate.
        /// </summary>
        public static string LocateButtonText {
            get {
                return ResourceManager.GetString("LocateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string LogOnAccountInformation {
            get {
                return ResourceManager.GetString("LogOnAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name and password bellow.
        /// </summary>
        public static string LogOnEnterCredentials {
            get {
                return ResourceManager.GetString("LogOnEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string LogOnFailed {
            get {
                return ResourceManager.GetString("LogOnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or, if You do not have an account please register here.
        /// </summary>
        public static string LogonIfNoAccountSentence {
            get {
                return ResourceManager.GetString("LogonIfNoAccountSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LogOnPassword {
            get {
                return ResourceManager.GetString("LogOnPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me on this computer.
        /// </summary>
        public static string LogOnRememberMe {
            get {
                return ResourceManager.GetString("LogOnRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOnSubmit {
            get {
                return ResourceManager.GetString("LogOnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string LogOnUserName {
            get {
                return ResourceManager.GetString("LogOnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LogOnWelcome {
            get {
                return ResourceManager.GetString("LogOnWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LongitudeText {
            get {
                return ResourceManager.GetString("LongitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested item cannot be found..
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} comments.
        /// </summary>
        public static string NumberOfCommentsPlural {
            get {
                return ResourceManager.GetString("NumberOfCommentsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} comment.
        /// </summary>
        public static string NumberOfCommentsSingular {
            get {
                return ResourceManager.GetString("NumberOfCommentsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} galleries.
        /// </summary>
        public static string NumberOfGalleriesPlural {
            get {
                return ResourceManager.GetString("NumberOfGalleriesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gallery.
        /// </summary>
        public static string NumberOfGalleriesSingular {
            get {
                return ResourceManager.GetString("NumberOfGalleriesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} photos.
        /// </summary>
        public static string NumberOfPhotosPlural {
            get {
                return ResourceManager.GetString("NumberOfPhotosPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} photo.
        /// </summary>
        public static string NumberOfPhotosSingular {
            get {
                return ResourceManager.GetString("NumberOfPhotosSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment has been added!.
        /// </summary>
        public static string PageFlashCommentPosted {
            get {
                return ResourceManager.GetString("PageFlashCommentPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent!.
        /// </summary>
        public static string PageFlashMessageSent {
            get {
                return ResourceManager.GetString("PageFlashMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string PhotoComments {
            get {
                return ResourceManager.GetString("PhotoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string PhotoCommentsAddComment {
            get {
                return ResourceManager.GetString("PhotoCommentsAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string PhotoCommentsAuthorComment {
            get {
                return ResourceManager.GetString("PhotoCommentsAuthorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string PhotoCommentsAuthorEmail {
            get {
                return ResourceManager.GetString("PhotoCommentsAuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address will not be shown or shared with anyone. It is only used to show your &lt;a href=&quot;http://www.gravatar.com&quot; target=&quot;_blank&quot;&gt;Gravatar&lt;/a&gt; if you have one (a unique image coupled to your email address)..
        /// </summary>
        public static string PhotoCommentsAuthorEmailHelp {
            get {
                return ResourceManager.GetString("PhotoCommentsAuthorEmailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string PhotoCommentsAuthorName {
            get {
                return ResourceManager.GetString("PhotoCommentsAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me on this computer.
        /// </summary>
        public static string PhotoCommentsAuthorRememberMe {
            get {
                return ResourceManager.GetString("PhotoCommentsAuthorRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string PhotoCommentsAuthorUrl {
            get {
                return ResourceManager.GetString("PhotoCommentsAuthorUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment by.
        /// </summary>
        public static string PhotoCommentsBy {
            get {
                return ResourceManager.GetString("PhotoCommentsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no comments yet, why don&apos;t you be the first to add one?.
        /// </summary>
        public static string PhotoCommentsEmpty {
            get {
                return ResourceManager.GetString("PhotoCommentsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Comment.
        /// </summary>
        public static string PhotoCommentsSubmit {
            get {
                return ResourceManager.GetString("PhotoCommentsSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string PhotoLinkLargeText {
            get {
                return ResourceManager.GetString("PhotoLinkLargeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the large version of the photo.
        /// </summary>
        public static string PhotoLinkLargeTitle {
            get {
                return ResourceManager.GetString("PhotoLinkLargeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string PhotoLinkNormalText {
            get {
                return ResourceManager.GetString("PhotoLinkNormalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the medium version of the photo.
        /// </summary>
        public static string PhotoLinkNormalTitle {
            get {
                return ResourceManager.GetString("PhotoLinkNormalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string PhotoLinkSmallText {
            get {
                return ResourceManager.GetString("PhotoLinkSmallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the small version of the photo.
        /// </summary>
        public static string PhotoLinkSmallTitle {
            get {
                return ResourceManager.GetString("PhotoLinkSmallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PhotoNavigateNext {
            get {
                return ResourceManager.GetString("PhotoNavigateNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PhotoNavigatePrevious {
            get {
                return ResourceManager.GetString("PhotoNavigatePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To: {0}.
        /// </summary>
        public static string PhotoNavigateTo {
            get {
                return ResourceManager.GetString("PhotoNavigateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string PhotoPublished {
            get {
                return ResourceManager.GetString("PhotoPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmbroideryItem&apos;s by date taken.
        /// </summary>
        public static string PhotosByDateTaken {
            get {
                return ResourceManager.GetString("PhotosByDateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string PhotosCalendar {
            get {
                return ResourceManager.GetString("PhotosCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0}.
        /// </summary>
        public static string PhotosDateTitleInMonth {
            get {
                return ResourceManager.GetString("PhotosDateTitleInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0}.
        /// </summary>
        public static string PhotosDateTitleInYear {
            get {
                return ResourceManager.GetString("PhotosDateTitleInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0}.
        /// </summary>
        public static string PhotosDateTitleOnDay {
            get {
                return ResourceManager.GetString("PhotosDateTitleOnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos with the search term &apos;{0}&apos;.
        /// </summary>
        public static string PhotosFoundFromSearch {
            get {
                return ResourceManager.GetString("PhotosFoundFromSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        public static string PhotoSizes {
            get {
                return ResourceManager.GetString("PhotoSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string PhotosOverview {
            get {
                return ResourceManager.GetString("PhotosOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos published {0}.
        /// </summary>
        public static string PhotosPublished {
            get {
                return ResourceManager.GetString("PhotosPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos tagged {0}.
        /// </summary>
        public static string PhotosTagged {
            get {
                return ResourceManager.GetString("PhotosTagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos taken {0}.
        /// </summary>
        public static string PhotosTaken {
            get {
                return ResourceManager.GetString("PhotosTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos with &apos;{0}&apos; in the title.
        /// </summary>
        public static string PhotosTitled {
            get {
                return ResourceManager.GetString("PhotosTitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string PhotoTags {
            get {
                return ResourceManager.GetString("PhotoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        public static string PhotoTaken {
            get {
                return ResourceManager.GetString("PhotoTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of QR code .DST embroidery file.
        /// </summary>
        public static string QRCodeEmbroGenName {
            get {
                return ResourceManager.GetString("QRCodeEmbroGenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string QRCodeVCARDAddressLabel {
            get {
                return ResourceManager.GetString("QRCodeVCARDAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string QRCodeVCARDNameLabel {
            get {
                return ResourceManager.GetString("QRCodeVCARDNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string QRCodeVCARDNotesLabel {
            get {
                return ResourceManager.GetString("QRCodeVCARDNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string QRCodeVCARDOrganizationLabel {
            get {
                return ResourceManager.GetString("QRCodeVCARDOrganizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string QRCodeVCARDPhoneLabel {
            get {
                return ResourceManager.GetString("QRCodeVCARDPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site URL.
        /// </summary>
        public static string QRCodeVCARDsiteURLLabel {
            get {
                return ResourceManager.GetString("QRCodeVCARDsiteURLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string QRCodeVCARDSurnameLabel {
            get {
                return ResourceManager.GetString("QRCodeVCARDSurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать.
        /// </summary>
        public static string RegisterViewModel_ConfirmPassword_ErrorMessage {
            get {
                return ResourceManager.GetString("RegisterViewModel_ConfirmPassword_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type an e-mail, please.
        /// </summary>
        public static string RegisterViewModel_Email_ErrorMessage {
            get {
                return ResourceManager.GetString("RegisterViewModel_Email_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be entered.
        /// </summary>
        public static string RegisterViewModel_Password_ErrorMessage {
            get {
                return ResourceManager.GetString("RegisterViewModel_Password_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchSubmit {
            get {
                return ResourceManager.GetString("SearchSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string SelectFileButtonTitle {
            get {
                return ResourceManager.GetString("SelectFileButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;None&gt;.
        /// </summary>
        public static string SelectListItemNone {
            get {
                return ResourceManager.GetString("SelectListItemNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backwards.
        /// </summary>
        public static string SlideshowGoBackwards {
            get {
                return ResourceManager.GetString("SlideshowGoBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwards.
        /// </summary>
        public static string SlideshowGoForwards {
            get {
                return ResourceManager.GetString("SlideshowGoForwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string SlideshowPause {
            get {
                return ResourceManager.GetString("SlideshowPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slower.
        /// </summary>
        public static string SlideshowSpeedDown {
            get {
                return ResourceManager.GetString("SlideshowSpeedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster.
        /// </summary>
        public static string SlideshowSpeedUp {
            get {
                return ResourceManager.GetString("SlideshowSpeedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Slideshow.
        /// </summary>
        public static string SlideshowStart {
            get {
                return ResourceManager.GetString("SlideshowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syndication Feed (Comments).
        /// </summary>
        public static string SyndicationFeedComments {
            get {
                return ResourceManager.GetString("SyndicationFeedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syndication Feed (Photos).
        /// </summary>
        public static string SyndicationFeedPhotos {
            get {
                return ResourceManager.GetString("SyndicationFeedPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolocation.
        /// </summary>
        public static string TabQRCodeLocation {
            get {
                return ResourceManager.GetString("TabQRCodeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TabQRcodeText {
            get {
                return ResourceManager.GetString("TabQRcodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show photos tagged {0}.
        /// </summary>
        public static string TagNavigateTo {
            get {
                return ResourceManager.GetString("TagNavigateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tags.
        /// </summary>
        public static string TagsShowAll {
            get {
                return ResourceManager.GetString("TagsShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top {0} Tags.
        /// </summary>
        public static string TagsShowTop {
            get {
                return ResourceManager.GetString("TagsShowTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsTitle {
            get {
                return ResourceManager.GetString("TagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0} at {1}.
        /// </summary>
        public static string TimeOnDateAtTime {
            get {
                return ResourceManager.GetString("TimeOnDateAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today at {0}.
        /// </summary>
        public static string TimeTodayAtTime {
            get {
                return ResourceManager.GetString("TimeTodayAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday at {0}.
        /// </summary>
        public static string TimeYesterdayAtTime {
            get {
                return ResourceManager.GetString("TimeYesterdayAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All times are in {0}.
        /// </summary>
        public static string TimeZoneOffsetInfo {
            get {
                return ResourceManager.GetString("TimeZoneOffsetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        public static string ValidationAuthorEmailEmpty {
            get {
                return ResourceManager.GetString("ValidationAuthorEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string ValidationAuthorEmailInvalid {
            get {
                return ResourceManager.GetString("ValidationAuthorEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name..
        /// </summary>
        public static string ValidationAuthorNameEmpty {
            get {
                return ResourceManager.GetString("ValidationAuthorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title..
        /// </summary>
        public static string ValidationMenuTitleEmpty {
            get {
                return ResourceManager.GetString("ValidationMenuTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a URL..
        /// </summary>
        public static string ValidationMenuUrlEmpty {
            get {
                return ResourceManager.GetString("ValidationMenuUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title..
        /// </summary>
        public static string ValidationPageTitleEmpty {
            get {
                return ResourceManager.GetString("ValidationPageTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid published date..
        /// </summary>
        public static string ValidationPhotoDatePublishedInvalid {
            get {
                return ResourceManager.GetString("ValidationPhotoDatePublishedInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid taken date..
        /// </summary>
        public static string ValidationPhotoDateTakenInvalid {
            get {
                return ResourceManager.GetString("ValidationPhotoDateTakenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a URL for the normal size of the photo..
        /// </summary>
        public static string ValidationPhotoUrlNormalEmpty {
            get {
                return ResourceManager.GetString("ValidationPhotoUrlNormalEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and try again..
        /// </summary>
        public static string ValidationSummaryGenericTitle {
            get {
                return ResourceManager.GetString("ValidationSummaryGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a message..
        /// </summary>
        public static string ValidationTextEmpty {
            get {
                return ResourceManager.GetString("ValidationTextEmpty", resourceCulture);
            }
        }
    }
}
